### ISSUE TITLE
Issue when doing ToA

### ISSUE THREAD

**Issue by Omtrw** [fnk93/Summoners-War-Bot#10]
Traceback (most recent call last):
  File "mycode_hive.py", line 21, in <module>
    a.doToa(1,90,600)
  File "D:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 1543, in doToa
    if 100 >= floor_id > self.trial_tower_list[difficulty]['cleared'] + 1:
TypeError: 'NoneType' object is not subscriptable

**Comment by fnk93** [comment]
See at #11 . Same should apply for this.
