### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by FR96** [fnk93/Summoners-War-Bot#16]
```
`  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\mybot.py", line 988, in finishScenario
    if not self.bot.do_scenario(scenario, stage_no_cleared, difficulty, clear_time):
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 1623, in do_scenario
    "pos_y": self.last_position['pos_y']}, clear_time, win_lose)
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 798, in BattleScenarioResult
    return self.call_api(self.c2_api, data)
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 238, in call_api
    raise e
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 227, in call_api
    self._check_response_data(res)
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 1670, in _check_response_data
    self.scenario_list[region['i']]['stage_list'][input_['stage_no']-1]['cleared'] = input_['cleared']
IndexError: list index out of range`
```
Happens when doing a loop (or using finishScenario()) of scenarios.
I'm not sure if the scenario list updates as soon as you finish one stage or you have to manually update it? either way, using a for loop of do_scenario or using the already written finishScenario (mybot.py) the error appears.

   Cheers

**Comment by fnk93** [comment]
I will need to check this. Seems like an issue with the update of the "scenario_list".

**Comment by fnk93** [comment]
As for my test account everything is running fine. Might be, because he already unlocked the scenarios.

Would you mind posting the entry out of your "log.log" file which looks something like this:
`[{'region_id': 1, 'difficulty': 1, 'cleared': 1, 'stage_list': [{'stage_no': 1, 'cleared': 1},  ...`

**Comment by FR96** [comment]
I'll try to create a new account and test it. 
This account has already finished the first region, I just ran the bot and apparently there's no error so far. I think last time around the same thing happend (fixing itself after region 1 is cleared). It might just be the first region that is causing trouble.  
Just to recap; if the region 1 isn't cleared, the bot does the next scenario that isn't cleared, let's say scenario 4; this scenario 4 finishes succesfully. In the next iteration, it tries to do scenario 5, but it raises an error when calling_api in BattleScenarioStart and the program crashes.
The next time you start it, it does scenario 5 succesfully, but then crashes on Scenario 6. And so on until it clears region 1.

**Comment by FR96** [comment]
```
`[{'region_id': 1, 'difficulty': 1, 'cleared': 1, 'stage_list': [{'stage_no': 1, 'cleared': 1}, {'stage_no': 2, 'cleared': 1}, {'stage_no': 3, 'cleared': 1}, {'stage_no': 4, 'cleared': 1}, {'stage_no': 5, 'cleared': 1}, {'stage_no': 6, 'cleared': 1}, {'stage_no': 7, 'cleared': 1}]}, {'region_id': 2, 'difficulty': 1, 'cleared': 0, 'stage_list': [{'stage_no': 1, 'cleared': 1}, {'stage_no': 2, 'cleared': 1}, {'stage_no': 3, 'cleared': 1}, {'stage_no': 4, 'cleared': 1}]}]
[09:41:34]: 2 5 1 [{'unit_id': 11329501342}, {'unit_id': 11329501848}, {'unit_id': 11329505042}] []
1189107061
1189107062
1189107063
[09:41:37]: Battle started: region 2, stage 5, difficulty 1
[09:41:47]: 1523536888 [{'unit_id': 1, 'result': 2}, {'unit_id': 2, 'result': 2}, {'unit_id': 3, 'result': 2}, {'unit_id': 4, 'result': 2}, {'unit_id': 7, 'result': 2}, {'unit_id': 5, 'result': 2}, {'unit_id': 6, 'result': 2}] [{'unit_id': 11329501342}, {'unit_id': 11329501848}, {'unit_id': 11329505042}] {'island_id': 1, 'pos_x': 10, 'pos_y': 12} 10 1
1189106306
[09:41:47]: Error when calling api: list index out of range
Traceback (most recent call last):
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\mycode_hive.py", line 164, in <module>
    a.do_scenario(i,j,1,10)
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 1630, in do_scenario
    "pos_y": self.last_position['pos_y']}, clear_time, win_lose)
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 797, in BattleScenarioResult
    return self.call_api(self.c2_api, data)
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 237, in call_api
    raise e
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 226, in call_api
    self._check_response_data(res)
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 1689, in _check_response_data
    self.scenario_list[region['i']]['stage_list'][input_['stage_no']-1]['cleared'] = input_['cleared']
IndexError: list index out of range`
```

Okay, now I'm more confused than before. Region 2 Scenario 5 obv. wasn't cleared, the code running was basically a for loop of do_scenario.
After running the code again, I got this: 
````

[{'region_id': 1, 'difficulty': 1, 'cleared': 1, 'stage_list': [{'stage_no': 1, 'cleared': 1}, {'stage_no': 2, 'cleared': 1}, {'stage_no': 3, 'cleared': 1}, {'stage_no': 4, 'cleared': 1}, {'stage_no': 5, 'cleared': 1}, {'stage_no': 6, 'cleared': 1}, {'stage_no': 7, 'cleared': 1}]}, {'region_id': 2, 'difficulty': 1, 'cleared': 0, 'stage_list': [{'stage_no': 1, 'cleared': 1}, {'stage_no': 2, 'cleared': 1}, {'stage_no': 3, 'cleared': 1}, {'stage_no': 4, 'cleared': 1}, {'stage_no': 5, 'cleared': 1}]}]
[09:46:04]: 2 6 1 [{'unit_id': 11329501342}, {'unit_id': 11329501848}, {'unit_id': 11329505042}] []
1189106563
1189106564
1189106565
[09:46:07]: Battle started: region 2, stage 6, difficulty 1
[09:46:37]: 1523537158 [{'unit_id': 1, 'result': 2}, {'unit_id': 2, 'result': 2}, {'unit_id': 3, 'result': 2}, {'unit_id': 4, 'result': 2}, {'unit_id': 7, 'result': 2}, {'unit_id': 5, 'result': 2}, {'unit_id': 6, 'result': 2}] [{'unit_id': 11329501342}, {'unit_id': 11329501848}, {'unit_id': 11329505042}] {'island_id': 1, 'pos_x': 10, 'pos_y': 12} 30 1
1189106596
[09:46:37]: Error when calling api: list index out of range
Traceback (most recent call last):
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\mybot.py", line 1508, in <module>
    autoplay.finishScenario(1)
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\mybot.py", line 988, in finishScenario
    if not self.bot.do_scenario(scenario, stage_no_cleared, difficulty, clear_time):
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 1630, in do_scenario
    "pos_y": self.last_position['pos_y']}, clear_time, win_lose)
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 797, in BattleScenarioResult
    return self.call_api(self.c2_api, data)
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 237, in call_api
    raise e
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 226, in call_api
    self._check_response_data(res)
  File "d:\LC LAUTI\Summoners-War-Bot-masterpy3\Summoners-War-Bot-master\api.py", line 1689, in _check_response_data
    self.scenario_list[region['i']]['stage_list'][input_['stage_no']-1]['cleared'] = input_['cleared']
IndexError: list index out of range
````
As you can see, second time it's actually running the finishScenario on mybot... not that it matters anyway.
