### ISSUE TITLE
Launch Issue

### ISSUE THREAD

**Issue by oddessax** [fnk93/Summoners-War-Bot#24]
Mate, it's soooo good to see you back on this project. Since the OTP drama i basically gave up hope for using this. I've fresh d/l'd the latest version and here's my error on launch.

` # Login-data:
    user = '##MYUSERNAME##'
    user_mail = '##MYEMAIL##'
    pw = '##MYPASSWORD##'
    # device id, leave empty if you don't know yours
    device_id = ''
    # device name configurable in api and qpyou, leave empty if you haven't prepared a configuration
    device = ''
    # set to your region code ('eu', etc.) find codes in api.py -> set_region
    region = 'gb'
    autoplay = Bot(user, user_mail, pw, device_id, device, region)`

`"C:\##HIDDEN##\python.exe" C:/##HIDDEN##/mybot.py
Traceback (most recent call last):
  File "C:/##HIDDEN##/mybot.py", line 1461, in <module>
    autoplay = Bot(user, user_mail, pw, device_id, device, region)
  File "C:/##HIDDEN##/mybot.py", line 38, in __init__
    self.uid, self.did, self.sessionkey, appID = QPYOU(device_id_, device_).hiveLogin(user_, pw_)
  File "C:\##HIDDEN##\qpyou.py", line 173, in hiveLogin
    rr = self.s2.post('https://hub.qpyou.cn/auth/login_proc', data='id={}&password=&dkagh={}'.format(user, MD5(password)), headers={'Cache-Control': 'max-age=0', 'Origin': 'https://hub.qpyou.cn', 'Upgrade-Insecure-Requests': '1',
  File "C:\##HIDDEN##\qpyou.py", line 28, in MD5
    m.update(i)
TypeError: Unicode-objects must be encoded before hashing

Process finished with exit code 1
`

**Comment by oddessax** [comment]
your doing a top job man; here's the new error I assume if i set device id etc it will fix it:

> Traceback (most recent call last):
  File "C:/##HIDDEN##/mybot.py", line 1461, in <module>
    autoplay = Bot(user, user_mail, pw, device_id, device, region)
  File "C:/##HIDDEN##/mybot.py", line 38, in __init__
    self.uid, self.did, self.sessionkey, appID = QPYOU(device_id_, device_).hiveLogin(user_, pw_)
TypeError: 'NoneType' object is not iterable

**Comment by oddessax** [comment]
interesting I just tried again and not working.
I originally had mail name and pass but have since added device id and same error. Will see if i can find any more info for you

**Comment by oddessax** [comment]
ok tried my other account and it worked; i'll have another look at the first account to see whats breaking it.

**Comment by oddessax** [comment]
Hey Fnk, anyway to contact you outside of git?

**Comment by oddessax** [comment]
3rd account same issue; now interesting thing is before OTP the 2 accounts that arent working now were the ones that would work and the one that is working now was blocked by OTP issues could the Nonetype issue relate to accounts that arent triggering any OTP stuff or just coincidence?

**Comment by oddessax** [comment]
Narrowed it down, the field that isnt being passed back is _UID last bit of code before it errors is around here. 


>         _uid = None
        if 'gdpr/login' in rr.headers['Location']:
            rr = self.s2.post('https://hub.qpyou.cn/userinfo/gdpr/done', data='', headers={'Cache-Control': 'max-age=0', 'Origin': 'https://hub.qpyou.cn', 'Upgrade-Insecure-Requests': '1', 'Content-Type': 'application/x-www-form-urlencoded',
                                                                                           'User-Agent': QPYOU.USER_AGENT_HUB, 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'DNT': '1', 'Referer': 'https://hub.qpyou.cn/userinfo/gdpr/login'}, allow_redirects=False)
        if 'c2shub://login?error_code' in rr.headers['Location']:
            sss = rr.headers['Location'].split('&')
            # print(rr.headers)
            _uid = sss[1].replace('uid=', '')
            sessionkey = sss[3].replace('sessionkey=', '')
            _did = sss[2].replace('did=', '')
            print(sss)
        if not _uid:
            return None
        return _uid, _did, sessionkey, appid
