### ISSUE TITLE
otp issue?

### ISSUE THREAD

**Issue by Omtrw** [fnk93/Summoners-War-Bot#27]
A friend tried your bot and is getting this error:
detected otp...
Traceback (most recent call last):
  File "hive.py", line 33, in <module>
    uid,did,sessionkey,appId=QPYOU(device_id, device).hiveLogin(my_hivelogin,my_password)
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\qpyou.py", line 182, in hiveLogin
    if 'class="join_otp"' in rr.content:
TypeError: a bytes-like object is required, not 'str'

Any thought?

**Comment by Omtrw** [comment]
fixed for otp, bug getting this:
Traceback (most recent call last):
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 297, in call_api
    if old_data
KeyError: 'ts_val'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hive.py", line 41, in <module>
    a.login()
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 1806, in login
    res = self.HubUserLogin()
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 1886, in HubUserLogin
    res = self.call_api(self.c2_api, data)
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 320, in call_api
    raise e
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 305, in call_api
    return self.call_api(path, data, True)
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 320, in call_api
    raise e
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 309, in call_api
    self._check_response_data(res)
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 2454, in _check_response_data
    self._updateBuildings(json.loads(res)["building_list"])
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 1546, in _updateBuildings
    self.occupy_islands_buildings()
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 1411, in occupy_islands_buildings
    index_found = find(buildings, "building master id", str(build_))
  File "C:\Users\Adrien\Desktop\Summoners-War-Bot-master\tools.py", line 55, in find
    raise ValueError
ValueError
