### ISSUE TITLE
Running mybot.py produces this error

### ISSUE THREAD

**Issue by SpellCraft** [fnk93/Summoners-War-Bot#9]
```py3
[17:05:49]: Doing daily wish.
Traceback (most recent call last):
  File ".\mybot.py", line 1451, in <module>
    autoplay.doDailyWish()
  File ".\mybot.py", line 476, in doDailyWish
    wish_outcome = self.bot.DoRandomWishItem()['wish_info']
  File "D:\Users\Nadya\Documents\GitHub\Summoners-War-Bot-Py3\api.py", line 949, in DoRandomWishItem
    extra_data = OrderedDict([('island_id', self.buildings[10]['island_id']),
KeyError: 10
```

**Comment by fnk93** [comment]
Did this account already build the temple of wishes?

**Comment by SpellCraft** [comment]
No, it hasn't as far as I'm aware, though it has the ability to do it.  What I was thinking, possibly attempting to create a function that builds missing/required buildings if not already present in **self.buildings** or something similar.

**Comment by fnk93** [comment]
Yeah, that's also my plan. This function will need to check whether an account is allowed to build the building. For now, this bot is not yet able to handle a freshly created account. Sorry about that.

**Comment by SpellCraft** [comment]
No worries. :)
